version: '3'
services:
  blankoclientbuild:
    build: .
    volumes:
      - "build-volume:/usr/src/app/build"
  blankoclient:
    image: nginx:latest
    volumes:
      - "build-volume:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=blankoclient"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:client.blankoapp.com"
    depends_on:
      - "blankoclientbuild"
    restart: always

volumes:
  build-volume:
