version: '3'
services:
  blankoclientbuild:
    build: .
    volumes:
      - "build-volume:/usr/src/app/build"
  blankoclient:
    ports:
      - "80:80"
    image: nginx:latest
    volumes:
      - "build-volume:/usr/share/nginx/html"
    depends_on:
      - "blankoclientbuild"
    restart: always

volumes:
  build-volume:
