version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: npm-install
          command: npm install
      - run:
          name: npm-build
          command: npm run build

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Login in via SSH
          command: | 
            ssh $USER@$HOST echo 'vanuit circle ci deploy' >> test.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - add_ssh_keys:
          fingerprints:
            - "08:ca:ec:21:65:8a:d4:f4:83:23:ae:9a:1e:50:36:85"
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
