version: 2
jobs:
  build:
    working_directory: ./
    docker:
      - image: circleci/node:8.11.3
    steps:
      - run:
        name: install-npm
        command: npm install
      - run:
        name: build,
        command: npm run build
