export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_TASKS = 'FETCH_TASKS'
export const TOGGLE_ADDPROJECT = 'TOGGLE_ADDPROJECT'
export const ADD_PROJECT = 'ADD_PROJECT'
