export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const FETCH_TASKS = 'FETCH_TASKS'
export const TOGGLE_ADDPROJECT = 'TOGGLE_ADDPROJECT'
export const ADD_PROJECT = 'ADD_PROJECT'

export const TOGGLE_ADDTASK = 'TOGGLE_ADDTASK'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const SET_PROJECT_DATA = 'SET_PROJECT_DATA'
export const SET_TASK_ACTIVE = 'SET_TASK_ACTIVE'

export const START_MES = 'START_MES'
export const STOP_MES = 'STOP_MES'
